site_name: Zheming Gao

nav:
    - Home: index.md
    - Publications: pub.md
    - Teaching: teach.md
    - Research: research.md 

theme:
  palette:
    scheme： default
    primary: blue grey



markdown_extensions:
  - attr_list

copyright: 
    Copyright &copy; Zheming Gao 2021